import { Link } from 'react-router-dom'
import LegalPage from '../components/LegalPage.jsx'
import { CONTACT_EMAIL, OPERATOR_NAME, OPERATOR_JURISDICTION_NOTE, PRIVACY_LAST_UPDATED, SITE_NAME } from '../utils/legalConstants.js'

const mailto = <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>

const sections = [
  {
    id: 'who-we-are',
    heading: '1. Who We Are',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            {SITE_NAME} is a community-run, coordinate-based research archive where members submit,
            review, and browse research entries organized by planet, domain, and depth layer. This
            policy explains what personal data we collect when you use the site, why we collect it, and
            what rights you have over it under the EU General Data Protection Regulation (GDPR) and its
            Dutch implementing act (the AVG — Algemene Verordening Gegevensbescherming).
          </>
        ),
      },
      {
        type: 'p',
        text: (
          <>
            For the purposes of the GDPR, {OPERATOR_NAME} ("we", "us", "our") is the data controller
            for the personal data described in this policy, {OPERATOR_JURISDICTION_NOTE}.
          </>
        ),
      },
    ],
  },
  {
    id: 'information-we-collect',
    heading: '2. Information We Collect',
    blocks: [
      {
        type: 'p',
        text: 'We collect only what the site needs to operate: account identity, the research content you choose to submit, and the technical data generated by using a web application. Specifically:',
      },
      {
        type: 'ul',
        items: [
          <><b>Email address</b> — collected at sign-up, used to identify your account and for account-related communication (verification codes, security notices, password resets).</>,
          <><b>Username and profile information</b> — your chosen username, first and last name (if provided), and your points/role (student, reviewer, or admin), all shown against your contributions and on the leaderboard.</>,
          <><b>Authentication information</b> — handled by our identity provider, Clerk (see §5). We never see or store your password; Clerk stores a securely hashed version and manages sign-in sessions on our behalf.</>,
          <><b>Profile photo (avatar)</b> — if you upload one, it's stored in our file storage (see §7) and is publicly visible next to your contributions.</>,
          <><b>User-generated archive entries</b> — the titles, summaries, technical content, tags, coordinate placements, and alternate-perspective notes you submit for peer review and, once approved, publication in the public archive.</>,
          <><b>Review content</b> — if you act as a reviewer, the fact-check outcome, difficulty rating, and any written notes you leave on another member's submission.</>,
          <><b>Uploaded attachments</b> — archive entries can reference up to a handful of supporting attachments. These are label/URL pairs you provide (links to external sources, images, or documents you host elsewhere) rather than raw files uploaded to our servers, with the exception of the avatar photo described above.</>,
          <><b>IP address</b> — your device's IP address is visible to our hosting infrastructure and to Clerk while it manages sign-in security (for example, recognizing whether a sign-in is coming from a device we've seen before). We do not separately log or store IP addresses in our own database.</>,
          <><b>Browser and device information</b> — Clerk records basic technical information about the browser and device used to sign in (browser name, operating system, approximate device type, and an approximate location derived from IP address) as part of its account-security features.</>,
          <><b>Cookies and local storage</b> — see §8 for the full list of what's set and why.</>,
        ],
      },
    ],
  },
  {
    id: 'why-we-collect',
    heading: '3. Why We Collect This Information',
    blocks: [
      {
        type: 'p',
        text: 'We process personal data for the following purposes and legal bases under GDPR Article 6:',
      },
      {
        type: 'ul',
        items: [
          <><b>Providing the service (contract, Art. 6(1)(b))</b> — creating and authenticating your account, letting you submit and review archive entries, calculating points and leaderboard rank, and showing your contribution history back to you.</>,
          <><b>Legitimate interests (Art. 6(1)(f))</b> — securing accounts against unauthorized access, preventing abuse of the review system (for example, blocking self-review and duplicate reviews of the same entry), and maintaining the technical operation of the site.</>,
          <><b>Consent (Art. 6(1)(a))</b> — where you actively choose to do something optional, such as uploading an avatar or signing in via a third-party OAuth provider.</>,
          <><b>Legal obligation (Art. 6(1)(c))</b> — where we're required to retain or disclose information to comply with the law.</>,
        ],
      },
    ],
  },
  {
    id: 'authentication-clerk',
    heading: '4. Authentication Through Clerk',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            Account creation, sign-in, and session management are handled by Clerk, Inc., our
            identity-provider sub-processor. Clerk stores your credentials (a securely hashed password,
            or your linked OAuth identity), issues and validates the session token that keeps you signed
            in, and applies its own account-security protections — such as checking new passwords against
            known data breaches, rate-limiting repeated failed sign-in attempts, and asking for an emailed
            verification code the first time you sign in from an unrecognized browser.
          </>
        ),
      },
      {
        type: 'p',
        text: (
          <>
            Clerk acts as an independent data processor for this authentication data under its own
            privacy policy, available at{' '}
            <a href="https://clerk.com/legal/privacy" target="_blank" rel="noopener noreferrer">clerk.com/legal/privacy</a>.
          </>
        ),
      },
    ],
  },
  {
    id: 'oauth',
    heading: '5. Signing In With Google or GitHub',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            Instead of a password, you can choose to sign in using your existing Google or GitHub
            account. If you do, that provider shares your name, email address, and profile photo with us
            (via Clerk) so we can create or match your account — we never receive or see your Google or
            GitHub password. You can review or revoke this connection at any time from your Google or
            GitHub account settings.
          </>
        ),
      },
    ],
  },
  {
    id: 'data-storage',
    heading: '6. Data Storage Using Supabase',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            Your profile, archive entries, reviews, and other application data are stored in a
            PostgreSQL database and file storage hosted by Supabase, our database sub-processor. Access
            to this data is restricted at the database level by Row Level Security policies, so that,
            for example, only you (or a reviewer acting on a pending submission) can read or modify
            records tied to your account — the database itself enforces this, not just the application
            code.
          </>
        ),
      },
      {
        type: 'p',
        text: (
          <>
            Supabase acts as an independent data processor under its own privacy policy, available at{' '}
            <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">supabase.com/privacy</a>.
          </>
        ),
      },
    ],
  },
  {
    id: 'cookies',
    heading: '7. Cookies and Similar Technologies',
    blocks: [
      {
        type: 'p',
        text: 'We do not use advertising or analytics trackers of any kind. The only cookies and browser-storage items set are strictly necessary ones, set by Clerk (our authentication provider) to keep you signed in and to protect the sign-in process itself:',
      },
      {
        type: 'ul',
        items: [
          <><b>Session cookies</b> (e.g. <code>__session</code>, <code>__client_uat</code>) — keep you signed in between page loads and let the application verify that a request is really coming from your authenticated session.</>,
          <><b>Bot-protection cookies</b> (e.g. <code>__cf_bm</code>, <code>_cfuvid</code>) — set by Cloudflare, which Clerk uses to distinguish real sign-in/sign-up attempts from automated abuse.</>,
          <><b>Local storage</b> — a small amount of non-cookie browser storage for interface preferences that never leaves your device: your light/dark theme choice, whether you've seen the homepage intro animation, and a short-lived cache of your member role used to render the navigation instantly on load.</>,
        ],
      },
      {
        type: 'p',
        text: 'Because these are all strictly necessary for the site to function (there is nothing optional to opt out of), we do not show a cookie-consent banner. You can still block or delete cookies via your browser settings, though doing so will sign you out and may prevent sign-in from working at all.',
      },
    ],
  },
  {
    id: 'security',
    heading: '8. Security Measures',
    blocks: [
      {
        type: 'p',
        text: 'We take reasonable technical and organizational measures to protect your data, including:',
      },
      {
        type: 'ul',
        items: [
          'All traffic to the site is encrypted in transit via HTTPS/TLS.',
          'Passwords are never handled or stored by us directly — Clerk stores only a securely hashed form and screens new passwords against known breach databases.',
          'Database access is enforced by Row Level Security policies at the database layer, not only by application-level checks.',
          'API requests to our database are authorized using signed, short-lived tokens tied to your authenticated session.',
          'Repeated failed sign-in attempts are rate-limited and temporarily locked out by our authentication provider.',
        ],
      },
      {
        type: 'p',
        text: 'No system is perfectly secure, and we cannot guarantee absolute security of information transmitted over the internet. If we become aware of a data breach affecting your personal data, we will notify affected users and the relevant supervisory authority as required by GDPR Article 33 and 34.',
      },
    ],
  },
  {
    id: 'data-retention',
    heading: '9. Data Retention',
    blocks: [
      {
        type: 'p',
        text: 'We retain personal data for as long as your account is active, plus a reasonable period afterward to handle disputes, enforce our terms, and comply with legal obligations.',
      },
      {
        type: 'p',
        text: (
          <>
            Archive entries and reviews are, by design, part of a public, collaboratively built research
            record. If you delete your account (see §11), we will remove your profile and account data,
            but entries and reviews you contributed may remain part of the public archive to preserve the
            integrity and continuity of community research — where feasible, we will disassociate this
            content from your identity rather than deleting it outright. If you'd prefer your published
            contributions be removed entirely rather than disassociated, say so in your deletion request
            and we will accommodate that where reasonably possible.
          </>
        ),
      },
    ],
  },
  {
    id: 'your-rights',
    heading: '10. Your Rights Under the GDPR',
    blocks: [
      {
        type: 'p',
        text: 'If you are located in the European Economic Area (or otherwise protected by GDPR/AVG), you have the right to:',
      },
      {
        type: 'ul',
        items: [
          <><b>Access</b> — request a copy of the personal data we hold about you.</>,
          <><b>Rectification</b> — request correction of inaccurate or incomplete data.</>,
          <><b>Erasure</b> — request deletion of your personal data (see §11).</>,
          <><b>Restriction</b> — request that we limit how we process your data in certain circumstances.</>,
          <><b>Portability</b> — request your data in a structured, commonly used, machine-readable format.</>,
          <><b>Objection</b> — object to processing based on our legitimate interests.</>,
          <><b>Withdraw consent</b> — where processing is based on consent, withdraw it at any time without affecting processing that already took place.</>,
          <><b>Lodge a complaint</b> — with your national data protection authority. In the Netherlands, this is the Autoriteit Persoonsgegevens (<a href="https://autoriteitpersoonsgegevens.nl" target="_blank" rel="noopener noreferrer">autoriteitpersoonsgegevens.nl</a>).</>,
        ],
      },
      {
        type: 'p',
        text: <>To exercise any of these rights, contact us at {mailto}. We will respond within one month, as required by GDPR Article 12(3).</>,
      },
    ],
  },
  {
    id: 'account-deletion',
    heading: '11. Requesting Account or Data Deletion',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            The site does not currently have a self-service "delete my account" button. To request
            deletion of your account and personal data, email {mailto} from the address associated with
            your account (or otherwise verify your identity if you no longer have access to it). Once
            verified, we will delete your profile and authentication records, subject to the archive
            retention note in §9, and confirm back to you once it's done.
          </>
        ),
      },
    ],
  },
  {
    id: 'third-parties',
    heading: '12. Third-Party Services We Use',
    blocks: [
      {
        type: 'p',
        text: 'We rely on a small number of specialist providers to run the site, each acting as a data processor on our behalf:',
      },
      {
        type: 'ul',
        items: [
          <><b>Clerk</b> — authentication, session management, and account security (§4).</>,
          <><b>Supabase</b> — database and file storage (§6).</>,
          <><b>Cloudflare</b> — bot and abuse protection during sign-in/sign-up, deployed as part of Clerk's infrastructure (§7).</>,
          <><b>Google / GitHub</b> — optional OAuth sign-in, only if you choose to use it (§5).</>,
          <><b>Our hosting provider</b> — serves the website itself and, like any web host, has access to standard request logs (IP address, requested URL, timestamp) generated by normal web traffic.</>,
        ],
      },
      {
        type: 'p',
        text: 'We do not sell personal data, and we do not share it with third parties for their own marketing purposes.',
      },
    ],
  },
  {
    id: 'international-transfers',
    heading: '13. International Data Transfers',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            Clerk, Supabase, Cloudflare, Google, and GitHub may process and store data in the United
            States or other countries outside the European Economic Area as part of their global
            infrastructure. Where personal data is transferred outside the EEA, these providers rely on
            appropriate safeguards recognized under GDPR Chapter V, such as the European Commission's
            Standard Contractual Clauses, to ensure your data remains protected.
          </>
        ),
      },
    ],
  },
  {
    id: 'childrens-privacy',
    heading: "14. Children's Privacy",
    blocks: [
      {
        type: 'p',
        text: 'The site is not directed at, and we do not knowingly collect personal data from, children under the age of 16 (the digital age of consent under the Dutch implementation of GDPR). If we become aware that we have collected personal data from a child under 16 without appropriate consent, we will delete it promptly. If you believe a child has provided us with personal data, please contact us.',
      },
    ],
  },
  {
    id: 'changes',
    heading: '15. Changes to This Policy',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            We may update this policy from time to time as the site evolves. When we do, we'll revise
            the "Last updated" date at the top of this page. For material changes — anything that
            meaningfully affects what data we collect or how we use it — we'll make reasonable efforts to
            give you additional notice, such as a banner within the app.
          </>
        ),
      },
    ],
  },
  {
    id: 'contact',
    heading: '16. Contact Us',
    blocks: [
      {
        type: 'p',
        text: (
          <>
            Questions about this policy, or requests relating to your personal data, can be sent to{' '}
            {mailto}. See also our <Link to="/terms">Terms of Service</Link>.
          </>
        ),
      },
    ],
  },
]

export default function PrivacyPolicy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated={PRIVACY_LAST_UPDATED}
      intro="How The SOLAR Archive collects, uses, and protects your personal data, and the rights you have over it under the GDPR/AVG."
      sections={sections}
      seoDescription="The SOLAR Archive's Privacy Policy — what data we collect, why, how Clerk and Supabase are used, and your rights under GDPR/AVG."
      path="/privacy"
    />
  )
}
